//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReferenceAsync {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAsync.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/queryDB", ReplyAction="http://tempuri.org/IService1/queryDBResponse")]
        string queryDB(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/queryDB", ReplyAction="http://tempuri.org/IService1/queryDBResponse")]
        System.Threading.Tasks.Task<string> queryDBAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/queryTypeDB", ReplyAction="http://tempuri.org/IService1/queryTypeDBResponse")]
        string queryTypeDB(string search, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/queryTypeDB", ReplyAction="http://tempuri.org/IService1/queryTypeDBResponse")]
        System.Threading.Tasks.Task<string> queryTypeDBAsync(string search, int type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApplication1.ServiceReferenceAsync.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReferenceAsync.IService1>, WindowsFormsApplication1.ServiceReferenceAsync.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string queryDB(string search) {
            return base.Channel.queryDB(search);
        }
        
        public System.Threading.Tasks.Task<string> queryDBAsync(string search) {
            return base.Channel.queryDBAsync(search);
        }
        
        public string queryTypeDB(string search, int type) {
            return base.Channel.queryTypeDB(search, type);
        }
        
        public System.Threading.Tasks.Task<string> queryTypeDBAsync(string search, int type) {
            return base.Channel.queryTypeDBAsync(search, type);
        }
    }
}
